# Generated by Django 3.2 on 2022-06-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('nombre_tema', models.CharField(max_length=100, verbose_name='Nombre del tema')),
                ('descripcion_tema', models.TextField(verbose_name='Descripción del tema')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'apps_temas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContenidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('nombre_unidad', models.CharField(max_length=10050, verbose_name='Nombre de la Unidad')),
                ('competencia_a_desarrollar', models.TextField(verbose_name='Competencia a desarrollar')),
                ('temas', models.ManyToManyField(to='temario.TemasModel')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'db_table': 'app_contenido',
                'ordering': ['order'],
            },
        ),
    ]
