# Generated by Django 3.2 on 2022-06-09 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contenidomodel',
            table='apps_contenido',
        ),
    ]
